### ISSUE TITLE
Feature Request: Allow more functionality to plot.klmerci and others by moving the location of ymin and ymax aesthetics

### ISSUE THREAD

**Issue by mlascaleia** [BagchiLab-Uconn/RSPPlme4#1]
Currently the function `plot.klmerci` and others similar are limited by the fact that the default aesthetics include `ymin = lwr` and `ymax = upr`. When you try to add in a new `ggplot2` function that includes a different `data` argument than the default, it will throw an error because there are no columns called `upr` or `lwr` in the new data.frame. Moving the `ymin` and `ymax` arguments to mapping aesthetics within `geom_ribbon` fixes this issue.

**Comment by djj4tree** [comment]
Did you try using the inherit.aes = FALSE call when adding a new layer with different data?  That usually fixes errors when adding new data to a ggplot. The default in most layers is to inherit the global aesthetics, but this allow you to ignore them and define layer specific aesthetics.

**Comment by robertbagchi** [comment]
Fixed! Just modified the autopilot functions. Good tip on inherit.aes Dan, didn't know that
